/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystem;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : sessionRep.java
//  @ Date : 16/02/2017
//  @ Author : 
//
//
import java.util.ArrayList;
import java.sql.*;

public class sessionRep implements sessionRepo {
	private ArrayList<Session> sessions;
        
        public sessionRep(){
            sessions = new ArrayList<Session>();
        }  
        
        public sessionRep(ArrayList list){
            sessions = list;
        }
        
        public void addSession(Session session, Connection conn){
            sessions.add(session); 
            write(conn,  session);
        }
        
        public Session getSession(Session session){
            return sessions.get(session.getId()); 
        }
        public void setSessions(ArrayList list){
            sessions = list; 
        }
        public ArrayList<Session> getAllSessions(){
            return sessions; 
        }
        
	public void write(Connection conn, Session session) {
            ArrayList list = getAllSessions();
            System.out.println("Writing to the database... ");
       
            try {   
                Statement st = conn.createStatement();
              
                String sql = "INSERT INTO SESSION VALUES (" + session.getId() + ", '"
                                                            + session.getSessionType() + "' , '" 
                                                            + session.getDate() + "' , '" 
                                                            + session.getTime() + "' , " 
                                                            + session.getPrice() + ")";
                st.executeUpdate(sql);

                st.close();
                }
            catch (SQLException ex) {
                System.out.println("SQLException error (1)");
                }
        }
	public ArrayList read(Connection conn) {
            System.out.println("Reading from the database... ");
            ArrayList list = new ArrayList();
            try {   
                Statement st = conn.createStatement();
                
                ResultSet rs=null;
                String sql = "SELECT * FROM SESSION";
                rs=st.executeQuery(sql);

                while(rs.next()){ 
                    Session sesh = new Session();
                    sesh.setId(rs.getInt("ID"));
                    sesh.setSessionType(rs.getString("SESSION_TYPE"));
                    sesh.setDate(rs.getString("DATE"));
                    sesh.setTime(rs.getString("TIME"));
                    sesh.setPrice(rs.getFloat("PRICE"));
                    list.add(sesh);
                    System.out.println(rs.getInt("ID")+"\t"+rs.getString("SESSION_TYPE")+
                            "\t"+rs.getString("DATE")+"\t"+rs.getString("TIME")+"\t"+rs.getString("PRICE"));
                    }
                    rs.close();
                    st.close();
                }
            catch (SQLException ex) {
                    System.out.println("SQLException failed ! ");
                } 
        
            sessions = list;
        
            System.out.println("sessions..." + list.size());
            return sessions;
            }

    @Override
    public void addInstructor(Instructor instruc, Connection conn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Instructor getInstructor(Instructor instructor) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public ArrayList<Instructor> getAllInstructor() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void write(Connection conn, Instructor instructor) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Skier getSkier(Skier skier) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public ArrayList<Skier> getAllSkier() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setSkiers(ArrayList list) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void updateSkier(Skier ski, Connection conn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void deleteSkier(Skier ski, Connection conn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void write(Connection conn, String str, Skier skier) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    //@Override
    //public ArrayList readInstructor(Connection conn) {
    //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

    //@Override
    //public ArrayList readSkier(Connection conn) {
    //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

    @Override
    public void setInstructors(ArrayList list) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void addSkier(Skier skier, Connection conn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void addDate(Maintenance dat, Connection conn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Maintenance getDate(Maintenance date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public ArrayList<Maintenance> getAllDate() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setDate(ArrayList list) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void updateDate(Maintenance dat, Connection conn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void write(Connection conn, String str, Maintenance date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void addBooking(Booking Booking, Connection conn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Booking getBooking(Booking Booking) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public ArrayList<Booking> getAllBooking() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setBookings(ArrayList list) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void updateBookings(Booking Booking, Connection conn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void deleteBooking(Booking Booking, Connection conn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void write(Connection conn, String str, Booking Booking) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}

