/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystem;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : sessionRepo.java
//  @ Date : 16/02/2017
//  @ Author : 
//
//
import java.sql.*;
import java.util.ArrayList;

public interface sessionRepo {
    public void addSession(Session sesh, Connection conn);
    public Session getSession(Session session);
    public ArrayList<Session> getAllSessions();   

    public void setSessions(ArrayList list);
    void write(Connection conn, Session session);
    
    public void addInstructor(Instructor instruc, Connection conn);
    public Instructor getInstructor(Instructor instructor);
    public ArrayList<Instructor> getAllInstructor();
    public void setInstructors(ArrayList list);
    //public ArrayList readInstructor(Connection conn);
    void write(Connection conn, Instructor instructor);
    
    public Skier getSkier(Skier skier);
    public ArrayList<Skier> getAllSkier();
    //public ArrayList readSkier(Connection conn);
    public void addSkier(Skier skier, Connection conn);
    public void setSkiers(ArrayList list);
    public void updateSkier(Skier ski, Connection conn);
    public void deleteSkier(Skier ski, Connection conn);
    void write(Connection conn, String str, Skier skier); 
    
    public void addDate(Maintenance dat, Connection conn);
    public Maintenance getDate(Maintenance date);
    public ArrayList<Maintenance> getAllDate();
    public void setDate(ArrayList list);
    public void updateDate(Maintenance dat, Connection conn);
    void write(Connection conn, String str, Maintenance date);  
    
    public void addBooking(Booking Booking, Connection conn);
    public Booking getBooking(Booking Booking );
    public ArrayList<Booking> getAllBooking();
    public void setBookings(ArrayList list);    
    public void updateBookings(Booking Booking , Connection conn);
    public void deleteBooking(Booking Booking , Connection conn);
    void write(Connection conn, String str, Booking Booking );
    
    public ArrayList read(Connection conn);
}