/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystem;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SessionController.java
//  @ Date : 16/02/2017
//  @ Author : 
//
//
import java.sql.*;
import java.util.*;

public class SessionController {
	private Session list;
        sessionRepo seshRepo = new sessionRep();
        private ArrayList<Session> activeSessions;

        public void register(int id, String sessionType, String date, String time, Double price, Connection conn){
             
             Session sesh = new Session();
             sesh.setId(id);
             sesh.setSessionType(sessionType);
             sesh.setDate(date);
             sesh.setTime(time);
             sesh.setPrice(price);
             seshRepo.addSession(sesh, conn);
         } 
        public void setSessionList(ArrayList list){             
              seshRepo.setSessions(list);
         }
        
         public void updateSessionList(Connection conn){             
              activeSessions = seshRepo.read(conn);
          } 
        
         public void viewDetails(int id){
            ArrayList list = seshRepo.getAllSessions();
            boolean found  = false;
            int i = 0;
            while (i<list.size() && !found){
                Session temp = (Session)list.get(i);
                if (id == temp.getId()){
                    System.out.print("Session details: \n Session type: " + temp.getSessionType() + 
                     "\n Date: " +  temp.getDate() + "\n Time: " + temp.getTime()+ "\n Price: "+ 
                     temp.getPrice()+"\n");
                    found = true;
                }
                i++;
                }  
            }
        public void viewAll(){
            ArrayList list = seshRepo.getAllSessions();
            for (int i = 0; i<list.size(); i++){
                Session temp = (Session)list.get(i);
                    System.out.print("Session details: \n id: " + temp.getId() + 
                            "\n Session type: " + temp.getSessionType() + 
                            "\n Date: " +  temp.getDate() + "\n Time: " + temp.getTime() + "\n Price: " + 
                            temp.getPrice() + "\n");
                }              
         }
        
        public void viewAllTraining(){
            ArrayList list = seshRepo.getAllSessions();
            for (int i = 0; i<list.size(); i++){
                Session temp = (Session)list.get(i);
                    if (temp.getSessionType().equals("Instructor")){
                    System.out.print("Session details: \n id: " + temp.getId() + 
                            "\n Session type: " + temp.getSessionType() + 
                            "\n Date: " +  temp.getDate() + "\n Time: " + temp.getTime() + "\n Price: " + 
                            temp.getPrice() + "\n");
                    }
                } 
         }
        
        public Session findById(int findThis){
            ArrayList list = seshRepo.getAllSessions();
            for (int i = 0; i<list.size(); i++){
                Session temp = (Session)list.get(i);
                    if (temp.getId() == findThis){
                        return temp;
                    }
                    
                } 
            return null;
         }
}

